title: 'chloethesis.github.io'
description: "welcome to my github"
baseurl: "/jekyll-theme-console-demo-hacker"
url: "https://b2a3e8.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://discord.gg/">discord</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
